/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bblioteca.eno;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Timer;
import java.util.TimerTask;

import javax.swing.JOptionPane;

/**
 *
 * @author V
 */
public class frmprin extends javax.swing.JFrame {

    /**
     * Creates new form frmprin
     */
    public frmprin() {
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(Color.white);
        URL url = this.getClass().getResource("livro.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jButton1.setText("Livros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel2.setText("Curso:");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bblioteca/eno/Eye-icon (1).png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel3.setText("Data de saída:");

        jLabel4.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel4.setText("Livro:");

        jTextField4.setEditable(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jButton3.setText("Reserva");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton4.setText("Locar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel6.setText("Quantidade de alunos no local:");

        jButton5.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bblioteca/eno/Sign-Add-icon.png"))); // NOI18N
        jButton5.setText("Adicionar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jRadioButton1.setText("Manhã");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jRadioButton2.setText("Tarde");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jRadioButton3.setText("Noite");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton6.setText("Limpar todos os dados");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton7.setText("Ver todos os dados cadastrados");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jButton9.setText("Livros locados");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bblioteca/eno/Books-1-icon.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bblioteca/eno/cooltext178176948376444.png"))); // NOI18N

        jButton8.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton8.setText("Limpar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel5.setText("Turno:");

        jButton10.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jButton10.setText("Multas");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel9.setText("Quantidade de computadores usados no local:");

        jButton11.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bblioteca/eno/Sign-Add-icon.png"))); // NOI18N
        jButton11.setText("Adicionar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel10.setText("Quantidade de visitas no local:");

        jButton12.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bblioteca/eno/Sign-Add-icon.png"))); // NOI18N
        jButton12.setText("Adicionar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jRadioButton4.setText("Manhã");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jRadioButton5.setText("Tarde");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jRadioButton6.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jRadioButton6.setText("Noite");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel11.setText("Turno:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel5)
                                    .addGap(7, 7, 7)
                                    .addComponent(jRadioButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButton3))
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jTextField3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton5))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton11)))))
                                .addGap(4, 4, 4))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel3))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton6)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField6)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(67, 67, 67)
                                .addComponent(jTextField4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton4)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jButton11))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jButton12))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton1)
                            .addComponent(jButton6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ver frm = new ver();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        livros frm = new livros();
        frm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        functions func = new functions();
        String nome_aluno = jTextField1.getText();
        String nome_livro = jTextField4.getText();
        String curso = jTextField2.getText();
        String data = jTextField6.getText();
        Boolean res2 = temMulta(nome_aluno);
        Boolean res3 = temLivro(nome_livro);
        String rd1 = jRadioButton4.getText();
        String rd2 = jRadioButton5.getText();
        String rd3 = jRadioButton6.getText();
        ResultSet rs = null;

        if (nome_aluno.equals("") || nome_livro.equals("") || curso.equals("") || jRadioButton4.isSelected() == false && jRadioButton5.isSelected() == false && jRadioButton6.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "Digite os dados para locar!");
        } else {
            if (res2 == false && res3 == true) {
                if (jRadioButton4.isSelected()) {
                    rs = func.execute("SELECT qtd FROM empre WHERE turno='" + rd1 + "';", "SELECT");
                } else if (jRadioButton5.isSelected()) {
                    rs = func.execute("SELECT qtd FROM empre WHERE turno='" + rd2 + "'; ", "SELECT");
                } else if (jRadioButton6.isSelected()) {
                    rs = func.execute("SELECT qtd FROM empre WHERE turno='" + rd3 + "';", "SELECT");
                }
                int quant_antigo2 = 0;
                try {
                    while (rs.next()) {
                        quant_antigo2 = rs.getInt("qtd");
                    }
                    if (jRadioButton4.isSelected()) {
                        int res = quant_antigo2 + 1;
                        func.execute("UPDATE empre SET qtd=" + res + " where turno='" + rd1 + "';", "INSERT");
                        jRadioButton4.setSelected(false);

                    } else if (jRadioButton5.isSelected()) {
                        int res = quant_antigo2 + 1;
                        func.execute("UPDATE empre SET qtd=" + res + " where turno='" + rd2 + "';", "INSERT");
                        jRadioButton5.setSelected(false);

                    } else if (jRadioButton6.isSelected()) {
                        int res = quant_antigo2 + 1;
                        func.execute("UPDATE empre SET qtd=" + res + " where turno='" + rd3 + "';", "INSERT");
                        jRadioButton6.setSelected(false);
                    }
                } catch (Exception e) {
                    System.out.println("" + e);
                }
                func.execute("INSERT INTO locado VALUES('" + nome_livro + "','" + nome_aluno + "','" + curso + "','" + data + "',0,'nao');", "INSERT");

                rs = func.execute("SELECT * FROM livros WHERE nome_livro = \"" + jTextField4.getText() + "\"", "SELECT");
                int quant_antigo = 0;
                try {
                    while (rs.next()) {
                        quant_antigo = rs.getInt("quantidade");
                    }
                    if (quant_antigo <= 0) {
                        JOptionPane.showMessageDialog(this, "Este livro está locado!");
                    } else {
                        int res = quant_antigo - 1;
                        func.execute("UPDATE livros SET quantidade=" + res + " where nome_livro='" + nome_livro + "'", "INSERT");
                        JOptionPane.showMessageDialog(this, "Inserido com sucesso");
                        jTextField1.setText("");
                        jTextField4.setText("");
                        jTextField2.setText("");
                    }
                } catch (Exception e) {
                    System.out.println("" + e);
                }

            } else if (res2 == true) {
                JOptionPane.showMessageDialog(this, "Este aluno está com multa!");
                jTextField1.setText("");
                jTextField4.setText("");
                jTextField2.setText("");
            } else if (res3 == false) {
                JOptionPane.showMessageDialog(this, "O livro não está disponível, está locado!");
                jTextField1.setText("");
                jTextField4.setText("");
                jTextField2.setText("");
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed
    public Boolean temLivro(String nome_livro) {
        functions func = new functions();
        Boolean res = false;
        try {
            ResultSet rs = func.execute("SELECT * FROM livros WHERE nome_livro='" + nome_livro + "'", "SELECT");
            int quant = 0;
            while (rs.next()) {//pegando quantidade de resultados
                quant = rs.getInt("quantidade");
            }
            if (quant <= 0) {
                res = false;
            } else {
                res = true;
            }

        } catch (Exception e) {
            System.out.println(e);
        }
        return res;
    }

    public void checarMulta() {
        functions func = new functions();
        try {
            ResultSet rs = func.execute("SELECT * FROM multa", "SELECT");
            while (rs.next()) {
                String nome_aluno = rs.getString("nome_aluno");
                int dias_passados = rs.getInt("dias_passados");
                if (dias_passados >= 10) {
                    func.execute("DELETE FROM multa WHERE dias_passados>=10;", "INSERT");
                } else {

                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    public Boolean temMulta(String nome) {
        functions func = new functions();
        Boolean res = false;
        try {
            ResultSet rs = func.execute("SELECT * FROM multa WHERE nome_aluno='" + nome + "'", "SELECT");
            rs.first();
            //pegando quantidade de resultados
            int quant = rs.getRow();
            if (quant <= 0) {
                res = false;
            } else {
                res = true;
            }

        } catch (Exception e) {
            System.out.println("" + e);
        }
        return res;
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        functions func = new functions();
        DateFormat sb2 = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        String data_final = sb2.format(date);
        jTextField6.setText("" + data_final);
        verifica();
        verifica();
        multa();
        checarMulta();
        checarMulta();
    }//GEN-LAST:event_formWindowOpened
    public void multa() {
        functions func = new functions();
        try {
            int hoje = Calendar.getInstance().get(Calendar.DAY_OF_MONTH);
            ResultSet rs = func.execute("SELECT * FROM multa;", "SELECT");
            while (rs.next()) {
                String nome_aluno = rs.getString("nome_aluno");
                String data_saida = rs.getString("data_saida");
                int dias = rs.getInt("dias_passados");
                String partes[] = data_saida.split("-");
                int dia_saida = Integer.parseInt(partes[2]);
                int res = (dia_saida - hoje) * -1;
                func.execute("UPDATE multa SET dias_passados=" + res + " WHERE data_saida=\"" + data_saida + "\"", "INSERT");
                //dias = rs.getInt("dias_passados");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void verifica() {
        functions func = new functions();
        try {
            int hoje = Calendar.getInstance().get(Calendar.DAY_OF_MONTH);
            int mes = Calendar.getInstance().get(Calendar.MONTH);
            mes = mes + 1;
            int ano = Calendar.getInstance().get(Calendar.YEAR);
            ResultSet rs = func.execute("SELECT * FROM locado", "SELECT");
            while (rs.next()) {
                String nome_livro = rs.getString("nome_livro");
                String data_saida = rs.getString("data_saida");
                int dias = rs.getInt("dias_passados");
                String partes[] = data_saida.split("-");
                int dia_saida = Integer.parseInt(partes[2]);
                int mes_locado = Integer.parseInt(partes[1]);
                int ano_locado = Integer.parseInt(partes[0]);
                if (mes_locado == mes) {
                    int res = (dia_saida - hoje) * - 1;
                    func.execute("UPDATE locado SET dias_passados=" + res + " WHERE data_saida=\"" + data_saida + "\"", "INSERT");
                } else {
                    int res = diferenca(dia_saida + "/" + mes_locado + "/" + ano_locado, hoje + "/" + mes + "/" + ano) * -1;
                    func.execute("UPDATE locado SET dias_passados=" + res + " WHERE data_saida=\"" + data_saida + "\"", "INSERT");
                }

                dias = rs.getInt("dias_passados");
                if (dias > 10) {
                    func.execute("UPDATE locado SET multa='sim' WHERE dias_passados=\"" + dias + "\"", "INSERT");
                } else {
                    func.execute("UPDATE locado SET multa='nao' WHERE dias_passados=\"" + dias + "\"", "INSERT");
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public int diferenca(String s1, String s2) {
        int daysBetween = 0;
        try {
            //String s1 = "18/09/2014"; 
            //String s2 = "01/01/2014";
            DateFormat f = DateFormat.getDateInstance();
            Date date1 = f.parse(s1);
            Date date2 = f.parse(s2);

//Here's the part where we get the days between two dates.
            Calendar day1 = Calendar.getInstance();
            Calendar day2 = Calendar.getInstance();
            day1.setTime(date1);
            day2.setTime(date2);
            daysBetween = day1.get(Calendar.DAY_OF_YEAR) - day2.get(Calendar.DAY_OF_YEAR);
//Some code just to show the result...
            f = DateFormat.getDateInstance(DateFormat.MEDIUM);
        } catch (Exception e) {

        }
        return daysBetween;
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        reserva frm = new reserva();
        frm.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        functions func = new functions();
        String rd1 = jRadioButton1.getText();
        String rd2 = jRadioButton2.getText();
        String rd3 = jRadioButton3.getText();
        int qtdaluno = Integer.parseInt(jTextField3.getText());
        ResultSet rs = null;
        if (jRadioButton1.isSelected()) {
            rs = func.execute("SELECT qtd FROM qtdalunos WHERE turno='" + rd1 + "';", "SELECT");
        } else if (jRadioButton2.isSelected()) {
            rs = func.execute("SELECT qtd FROM qtdalunos WHERE turno='" + rd2 + "'; ", "SELECT");
        } else if (jRadioButton3.isSelected()) {
            rs = func.execute("SELECT qtd FROM qtdalunos WHERE turno='" + rd3 + "';", "SELECT");
        }
        int quant_antigo = 0;
        try {
            while (rs.next()) {
                quant_antigo = rs.getInt("qtd");
            }
            if (jRadioButton1.isSelected()) {
                int res = quant_antigo + qtdaluno;
                func.execute("UPDATE qtdalunos SET qtd=" + res + " where turno='" + rd1 + "';", "INSERT");
                JOptionPane.showMessageDialog(this, "Salvo com sucesso");
                jTextField3.setText("");
                jRadioButton1.setSelected(false);

            } else if (jRadioButton2.isSelected()) {
                int res = quant_antigo + qtdaluno;
                func.execute("UPDATE qtdalunos SET qtd=" + res + " where turno='" + rd2 + "';", "INSERT");
                JOptionPane.showMessageDialog(this, "Salvo com sucesso");
                jTextField3.setText("");
                jRadioButton2.setSelected(false);

            } else if (jRadioButton3.isSelected()) {
                int res = quant_antigo + qtdaluno;
                func.execute("UPDATE qtdalunos SET qtd=" + res + " where turno='" + rd3 + "';", "INSERT");
                JOptionPane.showMessageDialog(this, "Salvo com sucesso");
                jTextField3.setText("");
                jRadioButton3.setSelected(false);
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um turno!");
            }
        } catch (Exception e) {
            System.out.println("" + e);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        jRadioButton1.setSelected(false);
        jRadioButton3.setSelected(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        jRadioButton2.setSelected(false);
        jRadioButton1.setSelected(false);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        functions func = new functions();
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente limpar todos os dados de alunos?");
        if (resposta == 0) {
            func.execute("UPDATE qtdalunos SET qtd=0;", "INSERT");
            func.execute("UPDATE pc SET qtd=0;", "INSERT");
            func.execute("UPDATE visita SET qtd=0;", "INSERT");
            func.execute("UPDATE empre SET qtd=0;", "INSERT");
            func.execute("UPDATE qtdreserva SET qtd=0;", "INSERT");
            func.execute("UPDATE devolucao SET qtd=0;", "INSERT");
        } else if (resposta == 1) {

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        qtd form = new qtd();
        form.setVisible(true);
        functions func = new functions();

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        locados frm = new locados();
        frm.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jTextField1.setText("");
        jTextField4.setText("");
        jTextField2.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        multa frm = new multa();
        frm.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        functions func = new functions();
        String rd1 = jRadioButton1.getText();
        String rd2 = jRadioButton2.getText();
        String rd3 = jRadioButton3.getText();
        int qtdaluno = Integer.parseInt(jTextField5.getText());
        ResultSet rs = null;
        if (jRadioButton1.isSelected()) {
            rs = func.execute("SELECT qtd FROM pc WHERE turno='" + rd1 + "';", "SELECT");
        } else if (jRadioButton2.isSelected()) {
            rs = func.execute("SELECT qtd FROM pc WHERE turno='" + rd2 + "'; ", "SELECT");
        } else if (jRadioButton3.isSelected()) {
            rs = func.execute("SELECT qtd FROM pc WHERE turno='" + rd3 + "';", "SELECT");
        }
        int quant_antigo = 0;
        try {
            while (rs.next()) {
                quant_antigo = rs.getInt("qtd");
            }
            if (jRadioButton1.isSelected()) {
                int res = quant_antigo + qtdaluno;
                func.execute("UPDATE pc SET qtd=" + res + " where turno='" + rd1 + "';", "INSERT");
                JOptionPane.showMessageDialog(this, "Salvo com sucesso");
                jTextField5.setText("");
                jRadioButton1.setSelected(false);

            } else if (jRadioButton2.isSelected()) {
                int res = quant_antigo + qtdaluno;
                func.execute("UPDATE pc SET qtd=" + res + " where turno='" + rd2 + "';", "INSERT");
                JOptionPane.showMessageDialog(this, "Salvo com sucesso");
                jTextField5.setText("");
                jRadioButton2.setSelected(false);

            } else if (jRadioButton3.isSelected()) {
                int res = quant_antigo + qtdaluno;
                func.execute("UPDATE pc SET qtd=" + res + " where turno='" + rd3 + "';", "INSERT");
                JOptionPane.showMessageDialog(this, "Salvo com sucesso");
                jTextField5.setText("");
                jRadioButton3.setSelected(false);
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um turno!");
            }
        } catch (Exception e) {
            System.out.println("" + e);
        }

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        functions func = new functions();
        String rd1 = jRadioButton1.getText();
        String rd2 = jRadioButton2.getText();
        String rd3 = jRadioButton3.getText();
        int qtdaluno = Integer.parseInt(jTextField7.getText());
        ResultSet rs = null;
        if (jRadioButton1.isSelected()) {
            rs = func.execute("SELECT qtd FROM visita WHERE turno='" + rd1 + "';", "SELECT");
        } else if (jRadioButton2.isSelected()) {
            rs = func.execute("SELECT qtd FROM visita WHERE turno='" + rd2 + "'; ", "SELECT");
        } else if (jRadioButton3.isSelected()) {
            rs = func.execute("SELECT qtd FROM visita WHERE turno='" + rd3 + "';", "SELECT");
        }
        int quant_antigo = 0;
        try {
            while (rs.next()) {
                quant_antigo = rs.getInt("qtd");
            }
            if (jRadioButton1.isSelected()) {
                int res = quant_antigo + qtdaluno;
                func.execute("UPDATE visita SET qtd=" + res + " where turno='" + rd1 + "';", "INSERT");
                JOptionPane.showMessageDialog(this, "Salvo com sucesso");
                jTextField7.setText("");
                jRadioButton1.setSelected(false);

            } else if (jRadioButton2.isSelected()) {
                int res = quant_antigo + qtdaluno;
                func.execute("UPDATE visita SET qtd=" + res + " where turno='" + rd2 + "';", "INSERT");
                JOptionPane.showMessageDialog(this, "Salvo com sucesso");
                jTextField7.setText("");
                jRadioButton2.setSelected(false);

            } else if (jRadioButton3.isSelected()) {
                int res = quant_antigo + qtdaluno;
                func.execute("UPDATE visita SET qtd=" + res + " where turno='" + rd3 + "';", "INSERT");
                JOptionPane.showMessageDialog(this, "Salvo com sucesso");
                jTextField7.setText("");
                jRadioButton3.setSelected(false);
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um turno!");
            }
        } catch (Exception e) {
            System.out.println("" + e);
        }

    }//GEN-LAST:event_jButton12ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed
    public void setLivro(String livro) {
        System.out.println(livro);
        jTextField4.setText(livro);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmprin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmprin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmprin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmprin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmprin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
