/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bblioteca.eno;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author V
 */
public class locados extends javax.swing.JFrame {

    /**
     * Creates new form locados
     */
    public locados() {
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(Color.orange);
        URL url = this.getClass().getResource("livro.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        digita = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel1.setText("Pesquisar:");

        digita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                digitaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                digitaKeyTyped(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "title 5"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel2.setText("LIVROS LOCADOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(digita, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(digita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void digitaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_digitaKeyReleased
        int qtd = digita.getText().length();

        if (qtd > 1) {
            DefaultTableModel lista = new DefaultTableModel();
            lista.addColumn("Nome");
            lista.addColumn("Livro");
            lista.addColumn("Curso");
            lista.addColumn("Data de saída");
            lista.addColumn("Dias passados");
            functions func = new functions();

            ResultSet rs = func.execute("SELECT * FROM locado WHERE nome_livro LIKE \"%" + digita.getText() + "%\" OR nome_aluno LIKE \"%" + digita.getText() + "%\" OR curso LIKE \"%" + digita.getText() + "%\" OR data_saida LIKE \"%" + digita.getText() + "%\" OR dias_passados LIKE \"%" + digita.getText() + "%\"", "SELECT");

            try {
                while (rs.next()) {
                    String aluno = rs.getString("nome_aluno");
                    String livro = rs.getString("nome_livro");
                    String curso = rs.getString("curso");
                    String ds = rs.getString("data_saida");
                    int dp = rs.getInt("dias_passados");
                    String[] acumula = {aluno,livro, curso, ds, "" + dp};
                    lista.addRow(acumula);

                }
                jTable2.setModel(lista);

            } catch (Exception e) {
                System.out.println("" + e);
            }
        }
        else{
        DefaultTableModel lista = new DefaultTableModel();
        lista.addColumn("Nome");
        lista.addColumn("Livro");
        lista.addColumn("Curso");
        lista.addColumn("Data de saída");
        lista.addColumn("Dias passados");
        functions func = new functions();
        ResultSet rs = func.execute("SELECT * FROM locado ORDER BY nome_aluno ASC;", "SELECT");
        try {
            while (rs.next()) {
                String nome = rs.getString("nome_aluno");
                String livro = rs.getString("nome_livro");
                String curso = rs.getString("curso");
                String dt = rs.getString("data_saida");
                int ds = rs.getInt("dias_passados");
                String[] nomes = {nome, livro, curso, dt, "" + ds};
                lista.addRow(nomes);
            }
        } catch (Exception e) {
            System.out.println("" + e);
        }

        jTable2.setModel(lista);
        }
    }//GEN-LAST:event_digitaKeyReleased

    private void digitaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_digitaKeyTyped

    }//GEN-LAST:event_digitaKeyTyped

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int selecionado = jTable2.getSelectedRow();
        String nome = jTable2.getValueAt(selecionado, 0).toString();
        String livro = jTable2.getValueAt(selecionado, 1).toString();
        String curso = jTable2.getValueAt(selecionado, 2).toString();
        String ds = jTable2.getValueAt(selecionado, 3).toString();
        int dp = Integer.parseInt(jTable2.getValueAt(selecionado, 4).toString());
        functions func = new functions();
        int resposta = JOptionPane.showConfirmDialog(this, "O livro '" + livro + "' foi devolvido?");
        if (resposta == 0) {
            try {
                DateFormat sb2 = new SimpleDateFormat("yyyy-MM-dd");
                Date date = new Date();
                String data_final = sb2.format(date);
                int res = qualTurno();
                int quant_antigo2 = 0;
                ResultSet rs = func.execute("SELECT qtd FROM devolucao;", "SELECT");
                try {
                    while (rs.next()) {
                    quant_antigo2 = rs.getInt("qtd");
                    }
                if(res == 0)
                {
                    int res2 = quant_antigo2 + 1;
                    func.execute("UPDATE devolucao SET qtd=" + res2 + " where turno='Manhã';", "INSERT");
                }
                else if (res == 1)
                {
                    int res2 = quant_antigo2 + 1;
                    func.execute("UPDATE devolucao SET qtd=" + res2 + " where turno='Tarde';", "INSERT");
                }
                else if (res == 2)
                {
                    int res2 = quant_antigo2 + 1;
                    func.execute("UPDATE devolucao SET qtd=" + res2 + " where turno='Noite';", "INSERT");
                }
                }catch(Exception e)
                {
                    System.out.println(""+e);
                }
                    
                if (dp > 10) {
                    JOptionPane.showMessageDialog(this, "O aluno(a) " + nome + " está com multa!");
                    func.execute("INSERT INTO multa VALUES('" + nome + "','" + data_final + "',0);", "INSERT");
                    func.execute("DELETE FROM locado WHERE nome_aluno='" + nome + "'AND nome_livro='" + livro + "' AND curso='" + curso + "' AND data_saida='" + ds + "';", "INSERT");
                    somar(livro);
                    locados frm = new locados();
                    frm.setVisible(true);
                    this.dispose();
                } else {
                    func.execute("DELETE FROM locado WHERE nome_aluno='" + nome + "'AND nome_livro='" + livro + "' AND curso='" + curso + "' AND data_saida='" + ds + "';", "INSERT");
                    somar(livro);
                    locados frm = new locados();
                    frm.setVisible(true);
                    this.dispose();
                }
            } catch (Exception e) {
                System.out.println(e);
            }

        } else if (resposta == 1) {

        }
    }//GEN-LAST:event_jTable2MouseClicked
    public void somar(String livro) {
        functions func = new functions();
        ResultSet rs = func.execute("SELECT * FROM livros;", "SELECT");
        int quant_antiga = 0;
        try {
            while (rs.next()) {
                quant_antiga = rs.getInt("quantidade");
            }
            int res = quant_antiga + 1;
            func.execute("UPDATE livros SET quantidade=" + res + " WHERE nome_livro='" + livro + "'", "INSERT");
        } catch (Exception e) {
            System.out.println("" + e);
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultTableModel lista = new DefaultTableModel();
        lista.addColumn("Nome");
        lista.addColumn("Livro");
        lista.addColumn("Curso");
        lista.addColumn("Data de saída");
        lista.addColumn("Dias passados");
        functions func = new functions();
        ResultSet rs = func.execute("SELECT * FROM locado ORDER BY nome_aluno ASC;", "SELECT");
        try {
            while (rs.next()) {
                String nome = rs.getString("nome_aluno");
                String livro = rs.getString("nome_livro");
                String curso = rs.getString("curso");
                String dt = rs.getString("data_saida");
                int ds = rs.getInt("dias_passados");
                String[] nomes = {nome, livro, curso, dt, "" + ds};
                lista.addRow(nomes);
            }
        } catch (Exception e) {
            System.out.println("" + e);
        }

        jTable2.setModel(lista);
    }//GEN-LAST:event_formWindowOpened
public int qualTurno()
{
 int res = 0;
 int i = JOptionPane.showOptionDialog(null, 
        "Qual é o turno?", 
        "Feedback", 
        JOptionPane.OK_CANCEL_OPTION, 
        JOptionPane.INFORMATION_MESSAGE, 
        null, 
        new String[]{"Manha", "Tarde","Noite"},null);
 return i;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(locados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(locados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(locados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(locados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new locados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField digita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
