/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bblioteca.eno;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author V
 */
public class qtd extends javax.swing.JFrame {

    /**
     * Creates new form qtd
     */
    public qtd() {
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(Color.orange);
        URL url = this.getClass().getResource("livro.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 90)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 90)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 90)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel5.setText("Tarde");

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel6.setText("Manhã");

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel7.setText("Noite");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alunos", "Computadores usados", "Visitas", "Devoluções", "Empréstimos", "Reservas" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(138, 138, 138)
                        .addComponent(jLabel7)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        functions func = new functions();
        ResultSet tn1 = func.execute("SELECT qtd FROM qtdalunos WHERE turno='Manhã';", "SELECT");
        ResultSet tn2 = func.execute("SELECT qtd FROM qtdalunos WHERE turno='Tarde';", "SELECT");
        ResultSet tn3 = func.execute("SELECT qtd FROM qtdalunos WHERE turno='Noite';", "SELECT");
        int qtd_atual;
        int qtd_atual2;
        int qtd_atual3;
        try {
            while (tn1.next()) {
                qtd_atual = tn1.getInt("qtd");
                jLabel1.setText("" + qtd_atual);
            }

            while (tn2.next()) {
                qtd_atual2 = tn2.getInt("qtd");
                jLabel2.setText("" + qtd_atual2);
            }
            while (tn3.next()) {
                qtd_atual3 = tn3.getInt("qtd");
                jLabel3.setText("" + qtd_atual3);
            }
        } catch (Exception e) {
            System.out.println("" + e);

        }

    }//GEN-LAST:event_formWindowOpened

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MousePressed
        
    }//GEN-LAST:event_jComboBox1MousePressed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        String sel = jComboBox1.getSelectedItem().toString();
        functions func = new functions();
        ResultSet tn1 = null;
        ResultSet tn2 = null;
        ResultSet tn3 = null;
        if(sel.equals("Alunos"))
        {
         tn1 = func.execute("SELECT qtd FROM qtdalunos WHERE turno='Manhã';", "SELECT");
         tn2 = func.execute("SELECT qtd FROM qtdalunos WHERE turno='Tarde';", "SELECT");
         tn3 = func.execute("SELECT qtd FROM qtdalunos WHERE turno='Noite';", "SELECT");   
        }
        else if(sel.equals("Computadores usados"))
        {
         tn1 = func.execute("SELECT qtd FROM pc WHERE turno='Manhã';", "SELECT");
         tn2 = func.execute("SELECT qtd FROM pc WHERE turno='Tarde';", "SELECT");
         tn3 = func.execute("SELECT qtd FROM pc WHERE turno='Noite';", "SELECT");   
        }
        else if(sel.equals("Visitas"))
        {
         tn1 = func.execute("SELECT qtd FROM visita WHERE turno='Manhã';", "SELECT");
         tn2 = func.execute("SELECT qtd FROM visita WHERE turno='Tarde';", "SELECT");
         tn3 = func.execute("SELECT qtd FROM visita WHERE turno='Noite';", "SELECT");   
        }
        else if(sel.equals("Devoluções"))
        {
         tn1 = func.execute("SELECT qtd FROM devolucao WHERE turno='Manhã';", "SELECT");
         tn2 = func.execute("SELECT qtd FROM devolucao WHERE turno='Tarde';", "SELECT");
         tn3 = func.execute("SELECT qtd FROM devolucao WHERE turno='Noite';", "SELECT");   
        }
        else if(sel.equals("Empréstimos"))
        {
         tn1 = func.execute("SELECT qtd FROM empre WHERE turno='Manhã';", "SELECT");
         tn2 = func.execute("SELECT qtd FROM empre WHERE turno='Tarde';", "SELECT");
         tn3 = func.execute("SELECT qtd FROM empre WHERE turno='Noite';", "SELECT");   
        }
        else if(sel.equals("Reservas"))
        {
         tn1 = func.execute("SELECT qtd FROM qtdreserva WHERE turno='Manhã';", "SELECT");
         tn2 = func.execute("SELECT qtd FROM qtdreserva WHERE turno='Tarde';", "SELECT");
         tn3 = func.execute("SELECT qtd FROM qtdreserva WHERE turno='Noite';", "SELECT");   
        }
        int qtd_atual;
        int qtd_atual2;
        int qtd_atual3;
        try {
            while (tn1.next()) {
                qtd_atual = tn1.getInt("qtd");
                jLabel1.setText("" + qtd_atual);
            }

            while (tn2.next()) {
                qtd_atual2 = tn2.getInt("qtd");
                jLabel2.setText("" + qtd_atual2);
            }
            while (tn3.next()) {
                qtd_atual3 = tn3.getInt("qtd");
                jLabel3.setText("" + qtd_atual3);
            }
        } catch (Exception e) {
            System.out.println("" + e);

        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(qtd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(qtd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(qtd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(qtd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new qtd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
